Models/Comment.cs
using System.ComponentModel.DataAnnotations;

namespace Active_Blog_Service.Models
{
    public class Comment
    {
        public int Id { get; set; }
        [MaxLength(100)]
        [MinLength(3)]
        public string CommentContent { get; set; }
        public DateTime CreatedDateTime { get; set; } = DateTime.Now;
        public int BlogId { get; set; }
        public string UserId { get; set; }

        public virtual Blog Blog { get; set; }
        public virtual User User { get; set; }

    }
}

Controllers/CommentController.cs
using Active_Blog_Service.Models;
using Active_Blog_Service.Repositories.Contracts;
using Active_Blog_Service.Services.Contracts;
using Active_Blog_Service.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Active_Blog_Service.Controllers
{
    public class CommentController : Controller
    {
        
        private readonly ICommentService _commentService;

        public CommentController(ICommentService commentService)
        {
            _commentService = commentService;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddComment(BlogCommentViewModel blogCommentViewModel)
        {
            await _commentService.AddCommentAsync(User,blogCommentViewModel);

            return RedirectToAction("Details", "Blog", new { id = blogCommentViewModel.Comment.BlogId });

        }
        [HttpPost]
        public async Task<IActionResult> EditComment(int commentId)
        {
            var comment = await _commentService.GetCommentAsync(commentId);
            return View(comment);
        }
        [HttpPost]
        public async Task<IActionResult> SaveCommentEdit(int commentId, string commentContent)
        {
            var comment = await _commentService.GetCommentAsync(commentId);

            await _commentService.EditCommentAsync(comment, commentContent);

            return RedirectToAction("Details", "Blog", new { id = comment.BlogId });
        }
        [HttpPost]
        public async Task<IActionResult> DeleteComment(int commentId)
        {
            var comment = await _commentService.GetCommentAsync(commentId);
            int blogId = comment.BlogId;
            await _commentService.DeleteCommentAsync(comment);

            return RedirectToAction("Details","Blog", new { id = blogId });
        }
    }
}

Views/Comment/EditComment.cshtml
@model Comment
@{
    ViewData["Title"] = "Edit Comment";
}
<div class="container mt-4">
    <h1 class="text-center mb-4">Edit Comment</h1>
    <form asp-action="SaveCommentEdit" asp-route-commentId="@Model.Id" asp-controller="Comment" method="post">
        <!-- Display validation errors -->
        <div asp-validation-summary="All" class="text-danger mt-3"></div>

        <!-- Comment Content -->
        <div class="form-floating mb-3">
            <input asp-for="CommentContent" id="inputContent" type="text" class="form-control" placeholder="Enter comment content" />
            <label asp-for="CommentContent">Comment Content</label>
            <span asp-validation-for="CommentContent" class="text-danger"></span>
        </div>

        <!-- Submit Button -->
        <div class="mt-4 mb-0">
            <div class="d-grid">
                <input type="submit" class="btn btn-primary btn-block" value="Save Changes" />
            </div>
        </div>
    </form>
    <br />
</div>
@section Scripts
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}